"""Domain models for AI-generated document analysis."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

ImportanceLevel = Literal["high", "medium", "low"]
EntityType = Literal[
    "person",
    "organization",
    "product",
    "project",
    "technology",
    "place",
    "paper",
    "concept",
    "other",
]


class DocumentSummary(BaseModel):
    """Short and detailed summaries of a source document."""

    model_config = ConfigDict(extra="forbid")

    short: str = Field(min_length=1)
    detailed: str = Field(min_length=1)


class KeyConcept(BaseModel):
    """A durable concept extracted from a source document."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    explanation: str = Field(min_length=1)
    importance: ImportanceLevel


class Definition(BaseModel):
    """A term and definition extracted from a source document."""

    model_config = ConfigDict(extra="forbid")

    term: str = Field(min_length=1)
    definition: str = Field(min_length=1)


class ImportantEntity(BaseModel):
    """A relevant person, organization, project, technology, or concept."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    type: EntityType
    description: str = Field(min_length=1)


class RelatedTopic(BaseModel):
    """A topic related to the source document."""

    model_config = ConfigDict(extra="forbid")

    topic: str = Field(min_length=1)
    reason: str = Field(min_length=1)


class DocumentAnalysis(BaseModel):
    """Validated structured analysis generated by the local model."""

    model_config = ConfigDict(extra="forbid")

    suggested_note_title: str = Field(min_length=1)
    summary: DocumentSummary
    key_concepts: list[KeyConcept] = Field(default_factory=list, max_length=10)
    definitions: list[Definition] = Field(default_factory=list, max_length=10)
    important_entities: list[ImportantEntity] = Field(default_factory=list, max_length=15)
    tags: list[str] = Field(default_factory=list, max_length=8)
    related_topics: list[RelatedTopic] = Field(default_factory=list, max_length=10)

    @field_validator("suggested_note_title")
    @classmethod
    def _clean_title(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if not cleaned:
            raise ValueError("Suggested note title must not be empty.")
        return cleaned

    @field_validator("tags")
    @classmethod
    def _validate_tags(cls, values: list[str]) -> list[str]:
        cleaned_tags: list[str] = []
        seen: set[str] = set()

        for value in values:
            cleaned = value.strip().lower().replace(" ", "-").lstrip("#")
            if not cleaned or cleaned in seen:
                continue
            seen.add(cleaned)
            cleaned_tags.append(cleaned)

        return cleaned_tags
