"""Domain models for AI-generated document analysis."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

ImportanceLevel = Literal["high", "medium", "low"]
DifficultyLevel = Literal["beginner", "intermediate", "advanced"]
EntityType = Literal[
    "person",
    "organization",
    "product",
    "project",
    "technology",
    "place",
    "paper",
    "concept",
    "other",
]


class DocumentSummary(BaseModel):
    """Short and detailed summaries of a source document."""

    model_config = ConfigDict(extra="forbid")

    short: str = Field(min_length=1)
    detailed: str = Field(min_length=1)


class KeyConcept(BaseModel):
    """A durable concept extracted from a source document."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    explanation: str = Field(min_length=1)
    importance: ImportanceLevel


class Definition(BaseModel):
    """A term and definition extracted from a source document."""

    model_config = ConfigDict(extra="forbid")

    term: str = Field(min_length=1)
    definition: str = Field(min_length=1)


class ImportantEntity(BaseModel):
    """A relevant person, organization, project, technology, or concept."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    type: EntityType
    description: str = Field(min_length=1)


class RelatedTopic(BaseModel):
    """A topic related to the source document."""

    model_config = ConfigDict(extra="forbid")

    topic: str = Field(min_length=1)
    reason: str = Field(min_length=1)


class QuestionAnswer(BaseModel):
    """A question and its answer extracted from the source document."""

    model_config = ConfigDict(extra="forbid")

    question: str = Field(min_length=1)
    answer: str = Field(min_length=1)


class Flashcard(BaseModel):
    """A flashcard with front (term/question) and back (definition/answer)."""

    model_config = ConfigDict(extra="forbid")

    front: str = Field(min_length=1)
    back: str = Field(min_length=1)


class MultipleChoiceQuestion(BaseModel):
    """A multiple choice question with options and correct answer."""

    model_config = ConfigDict(extra="forbid")

    question: str = Field(min_length=1)
    options: list[str] = Field(min_length=2, max_length=6)
    correct_answer: str = Field(min_length=1)
    explanation: str = Field(default="")


class ShortAnswerQuestion(BaseModel):
    """A short-answer question."""

    model_config = ConfigDict(extra="forbid")

    question: str = Field(min_length=1)
    answer: str = Field(min_length=1)


class LongAnswerQuestion(BaseModel):
    """A long-answer question requiring detailed explanation."""

    model_config = ConfigDict(extra="forbid")

    question: str = Field(min_length=1)
    answer: str = Field(min_length=1)


class RevisionNote(BaseModel):
    """A concise revision note for quick review."""

    model_config = ConfigDict(extra="forbid")

    heading: str = Field(min_length=1)
    points: list[str] = Field(min_length=1, max_length=10)


class ExtractedMetadata(BaseModel):
    """Structured metadata extracted from the source document."""

    model_config = ConfigDict(extra="forbid")

    author: str = Field(default="")
    word_count: int = Field(default=0, ge=0)
    page_count: int = Field(default=0, ge=0)
    language: str = Field(default="en")
    source_url: str = Field(default="")
    creation_date: str = Field(default="")
    publisher: str = Field(default="")
    version: str = Field(default="")
    license: str = Field(default="")


class DocumentAnalysis(BaseModel):
    """Validated structured analysis generated by the local model."""

    model_config = ConfigDict(extra="forbid")

    suggested_note_title: str = Field(min_length=1)
    summary: DocumentSummary
    keywords: list[str] = Field(default_factory=list, max_length=15)
    categories: list[str] = Field(default_factory=list, max_length=5)
    reading_time_minutes: int = Field(default=0, ge=0)
    difficulty: DifficultyLevel = "intermediate"
    key_concepts: list[KeyConcept] = Field(default_factory=list, max_length=10)
    definitions: list[Definition] = Field(default_factory=list, max_length=10)
    important_entities: list[ImportantEntity] = Field(default_factory=list, max_length=15)
    tags: list[str] = Field(default_factory=list, max_length=8)
    related_topics: list[RelatedTopic] = Field(default_factory=list, max_length=10)
    suggested_related_notes: list[str] = Field(default_factory=list, max_length=10)
    suggested_backlinks: list[str] = Field(default_factory=list, max_length=10)
    questions_and_answers: list[QuestionAnswer] = Field(default_factory=list, max_length=10)
    flashcards: list[Flashcard] = Field(default_factory=list, max_length=15)
    multiple_choice_questions: list[MultipleChoiceQuestion] = Field(
        default_factory=list, max_length=10,
    )
    short_answer_questions: list[ShortAnswerQuestion] = Field(
        default_factory=list, max_length=10,
    )
    long_answer_questions: list[LongAnswerQuestion] = Field(
        default_factory=list, max_length=5,
    )
    revision_notes: list[RevisionNote] = Field(default_factory=list, max_length=10)
    extracted_metadata: ExtractedMetadata = Field(default_factory=ExtractedMetadata)

    @field_validator("suggested_note_title")
    @classmethod
    def _clean_title(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if not cleaned:
            raise ValueError("Suggested note title must not be empty.")
        return cleaned

    @field_validator("tags")
    @classmethod
    def _validate_tags(cls, values: list[str]) -> list[str]:
        cleaned_tags: list[str] = []
        seen: set[str] = set()

        for value in values:
            cleaned = value.strip().lower().replace(" ", "-").lstrip("#")
            if not cleaned or cleaned in seen:
                continue
            seen.add(cleaned)
            cleaned_tags.append(cleaned)

        return cleaned_tags

    @field_validator("keywords")
    @classmethod
    def _validate_keywords(cls, values: list[str]) -> list[str]:
        cleaned: list[str] = []
        seen: set[str] = set()
        for value in values:
            word = value.strip().lower()
            if not word or word in seen:
                continue
            seen.add(word)
            cleaned.append(word)
        return cleaned

    @field_validator("categories")
    @classmethod
    def _validate_categories(cls, values: list[str]) -> list[str]:
        cleaned: list[str] = []
        seen: set[str] = set()
        for value in values:
            word = value.strip().title()
            if not word or word in seen:
                continue
            seen.add(word)
            cleaned.append(word)
        return cleaned
